Description : This program detects breast cancer, based off data.
import libraries

In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

In [2]:
df = pd.read_csv("/content/Copy of breast-cancer-wisconsin-csv.xls")


In [3]:
df.iloc[0] = [1000025, 5	,1,	1,	1,	2,	1,	3,	1,	1,	2]
df.rename(columns={'1000025':'Sample code number' ,'5': 'Clump Thickness' ,'1': 'Uniformity of Cell Size' , '1.1':'Uniformity of Cell Shape' ,'1.2': 'Marginal Adhesion' , '2':'Single Epithelial Cell Size' ,'1.3': 'Bare Nuclei' , '3':'Bland Chromatin' , '1.4':'Normal Nucleoli' , '1.5':'Mitoses' , '2.1':'Class:(2 for benign, 4 for malignant)'},inplace=True)
df.head(5)

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1015425                3                        1   
2             1016277                6                        8   
3             1017023                4                        1   
4             1017122                8                       10   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         1                  1                            2   
2                         8                  1                            3   
3                         1                  3                            2   
4                        10                  8                            7   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  \
0            1                3                1        1   
1            2                3                1        1   
2            4                3                7        1   
3            1                3                1        1   
4           10                9                7        1   

   Class:(2 for benign, 4 for malignant)  
0                                      2  
1                                      2  
2                                      2  
3                                      2  
4                                      4

In [4]:
#Count the number of rows and columns
df.shape

(682, 11)

Number of Instances: 699 (as of 15 July 1992)

Number of Attributes: 10 plus the class attribute

Attribute Information: (class attribute has been moved to last column)

   #  Attribute  -                       Domain
   -- -----------------------------------------
   1. Sample code number -                id number
   2. Clump Thickness -                  1 - 10
   3. Uniformity of Cell Size  -         1 - 10
   4. Uniformity of Cell Shape  -        1 - 10
   5. Marginal Adhesion            -     1 - 10
   6. Single Epithelial Cell Size  -     1 - 10
   7. Bare Nuclei                   -    1 - 10
   8. Bland Chromatin                -   1 - 10
   9. Normal Nucleoli                 -  1 - 10
   10. Mitoses                          - 1 - 10
11. Class:                            (2 for benign, 4 for malignant)

Missing attribute values: 16

   There are 16 instances in Groups 1 to 6 that contain a single missing 
   (i.e., unavailable) attribute value, now denoted by "?".  

Class distribution:
 
   Benign: 458 (65.5%)
   Malignant: 241 (34.5%)

In [5]:
#Split the data into dependent(X) and independent(Y) data sets
X = df.iloc[: , 1:9].values
Y = df.iloc[: , 10].values

In [6]:
#Split the data into 75% training data and 25% testing
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size = 0.25 , random_state = 0)

In [7]:
#Create a function for the models
def models(X_train,Y_train):

  #Logistic Regression
  from sklearn.linear_model import LogisticRegression
  log = LogisticRegression(random_state = 0)
  log.fit(X_train,Y_train)

  #Decision Tree
  from sklearn.tree import DecisionTreeClassifier
  tree = DecisionTreeClassifier(criterion = 'entropy' , random_state = 0)
  tree.fit(X_train, Y_train)

  #Random Forest Classifier
  from sklearn.ensemble import RandomForestClassifier
  forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy' , random_state = 0)
  forest.fit(X_train,Y_train)

  #Print the models accuracy on the training data 
  print('[0] Logistic Regression Training Accuracy:', log.score(X_train,Y_train))
  print('[1] Decision Tree Classifier Training Accuracy:', tree.score(X_train,Y_train))
  print('[2] Random Forest Classifier Training Accuracy:', forest.score(X_train,Y_train))

  return log,tree,forest

In [8]:
#Getting all of the models
model = models(X_train,Y_train)

[0] Logistic Regression Training Accuracy: 0.974559686888454
[1] Decision Tree Classifier Training Accuracy: 1.0
[2] Random Forest Classifier Training Accuracy: 0.9921722113502935


In [9]:
#Test model accuracy on test data on confusion matrix
from sklearn.metrics import confusion_matrix
for i in range(len(model)):
  print('Model' , i)
  cm = confusion_matrix(Y_test, model[i].predict(X_test))
  TP = cm[0][0]
  FP = cm[0][1]
  TN = cm[1][1]
  FN = cm[1][0]
  print(cm)
  print('Testing Accuracy =',( TP + TN )/(TP + TN + FP + FN))
  print()

Model 0
[[109   3]
 [  1  58]]
Testing Accuracy = 0.9766081871345029

Model 1
[[108   4]
 [  4  55]]
Testing Accuracy = 0.9532163742690059

Model 2
[[110   2]
 [  1  58]]
Testing Accuracy = 0.9824561403508771



In [10]:
#Print the prediction of Random Forest Classifier model
pred = model[2].predict(X_test)
print(pred)
print()
print(Y_test)

[2 2 4 2 2 4 2 2 2 4 4 2 4 2 2 4 4 4 2 4 4 2 2 2 4 2 2 2 2 2 2 2 4 4 2 2 2
 4 2 2 2 2 2 4 2 2 4 4 2 4 2 2 4 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 4 4 2 2 4 2 2 4 2 2 4 2 2 4 2 2 2 2 4 4 4 2 4 4 2 2 4 4 4 4 2 2 4 2 2 2
 2 2 4 2 2 2 4 2 2 2 4 2 2 4 4 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 4 4 4 2 4 4 2
 4 2 4 4 4 4 2 2 2 2 2 4 2 4 2 2 2 2 2 4 2 2 2]

[2 2 4 2 2 4 2 2 2 4 4 2 4 2 2 4 4 4 2 4 4 2 2 2 4 2 2 2 2 2 2 2 4 2 2 2 2
 4 2 2 2 2 2 4 2 2 4 4 2 4 2 2 4 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 4 4 2 2 4 2 2 4 2 2 4 2 2 4 2 2 2 2 4 4 4 2 4 4 2 2 4 4 4 4 2 2 4 2 2 2
 2 2 4 2 2 2 4 2 2 2 4 2 4 4 4 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 4 4 4 2 4 4 2
 4 2 4 4 4 4 2 2 2 2 2 4 2 4 2 2 2 2 2 4 2 2 2]


In [11]:
import pickle
# create an iterator object with write permission - model.pkl
with open('breast_model_pkl', 'wb') as files:
    pickle.dump(pred, files)